# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rpc/ThingService.proto for package 'rpc'

require 'grpc'
require 'rpc/ThingService_pb'

module Rpc
  module ThingService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.ThingService'

      rpc :GetThing, GetThingRequest, GetThingResponse
      rpc :GetThings, GetThingsRequest, stream(Thing)
      rpc :CreateThings, stream(Thing), CreateThingsResponse
      rpc :CreateThingsInStream, stream(Thing), stream(Thing)
      # Error calls
      rpc :GetFail, GetThingRequest, GetThingResponse
      rpc :GetFieldErrorFail, GetThingRequest, GetThingResponse
      rpc :GetException, GetThingRequest, GetThingResponse
      rpc :GetUncaughtException, GetThingRequest, GetThingResponse
    end

    Stub = Service.rpc_stub_class
  end
end
