# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/ThingService.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "rpc.GetThingRequest" do
    optional :id, :int64, 1
  end
  add_message "rpc.GetThingResponse" do
    optional :thing, :message, 1, "rpc.Thing"
  end
  add_message "rpc.GetThingsRequest" do
  end
  add_message "rpc.CreateThingsResponse" do
    repeated :things, :message, 1, "rpc.Thing"
  end
  add_message "rpc.Thing" do
    optional :id, :int64, 1
    optional :name, :string, 2
  end
end

module Rpc
  GetThingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetThingRequest").msgclass
  GetThingResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetThingResponse").msgclass
  GetThingsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetThingsRequest").msgclass
  CreateThingsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.CreateThingsResponse").msgclass
  Thing = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Thing").msgclass
end
